Introduction

In [2]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
t = (1,2,3,4,5)
arr = np.array(t)
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(t)

tuple

In [ ]:
lis = list(arr)

In [ ]:
lis

[1, 2, 3, 4, 5]

In [ ]:
type(lis)

list

Array dimensions

In [ ]:
arr = np.array(45)

In [ ]:
arr.ndim

0

In [ ]:
arr

array(45)

1D

In [ ]:
arr = np.array((42,34,455))
arr.ndim

1

In [ ]:
arr

array([ 42,  34, 455])

2-D

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

In [ ]:
mat = np.mat(np.array([[1,2,3],[4,5,6]]))

In [ ]:
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
type(mat)

numpy.matrix

In [ ]:
mat.ndim

2

3-D

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3,],[3,4,5]]])

In [ ]:
arr.ndim

3

In [ ]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5]]])

Higher Dimensional Arrays

In [ ]:
arr  =np.array([1,2,3], ndmin = 5)

In [ ]:
arr

array([[[[[1, 2, 3]]]]])

In [ ]:
arr.ndim

5

Checking Shape

In [ ]:
arr  =np.array([[1,2,3],[4,5,6]])


In [ ]:
arr.shape

(2, 3)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]]])

In [ ]:
arr.shape

(2, 2, 3)

In [ ]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5]]])

Arrange

In [3]:
pressures = np.arange(0,5500,500)

In [4]:
pressures

array([   0,  500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000])

In [6]:
pressures.ndim

1

Linspace

In [7]:
saturations = np.linspace(0,1,100)
saturations

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [8]:
saturations.shape

(100,)

zeros(A X B)

In [3]:
zero = np.zeros((50,50))
zero

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
zero[1][2] = 30
zero

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., 30., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

ones

In [5]:
p = np.ones((50,10))
p

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 

In [8]:
pi = 500
p*pi

array([[500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 50

eye: creating identity matrix

In [9]:
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.zeros((8,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])